version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5433'
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - pgdata:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: leda-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '80:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_API_SECRET=${PINATA_API_SECRET}
      - PINATA_URL=${PINATA_URL}
      - PINATA_GATEWAY_URL=${PINATA_GATEWAY_URL}
    ports:
      - '3333:3333' # expose-to-the-world : only-in-the-docker
    container_name: leda-api
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
  pgadmin-data:
