version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: leda-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '80:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data:
