name: Build and publish Leda Api Dev

on:
  push:
    branches: [root/continuos-deployment]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t ledaapi .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Tag image
        run: docker tag ledaapi registry.digitalocean.com/metis/ledaapi:${{ secrets.DIGITALOCEAN_APP_TAG }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/metis/ledaapi:${{ secrets.DIGITALOCEAN_APP_TAG }}
      - name: Launch image
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --wait
